@echo off
cd /d "%~dp0"
echo Iniciando backend Metashape...
start /B python app.py > logs\backend.log 2>&1
echo Esperando 5 segundos...
timeout /t 5 /nobreak >nul
echo Iniciando ngrok...
start /B ngrok http 8000 --log=stdout > logs\ngrok.log 2>&1
echo Esperando 10 segundos para que ngrok se conecte...
timeout /t 10 /nobreak >nul
echo Actualizando Render con la URL de ngrok...
python auto_url.py >> logs\auto_url.log 2>&1
echo Servidor listo
