"""Compatibilidad temporal para el backend existente.

Este modulo preserva el contrato interno mientras el proyecto migra a
`backend.core.*`. El resto del codigo puede seguir importando `backend.runtime`
sin cambios inmediatos.
"""

from backend.core.frontend import frontend_dist_path as _frontend_dist_path
from backend.core.frontend import serve_frontend_index
from backend.core.naming import DEFAULT_CAMERA_MODEL, DEFAULT_PROJECT_NAME, normalizar_modelo_camara, sanitizar_nombre_proyecto
from backend.core.paths import (
    BASE_DIR,
    CONTOURS_SCRIPT,
    DATASET_DIR as RUTA_IMAGENES,
    EARTH_RADIUS,
    FRONTEND_DIST_DIR,
    FRONTEND_INDEX_FILE,
    LOGS_DIR,
    MAIN_SCRIPT,
    MAX_TILE_ZOOM,
    METASHAPE_EXE,
    OVERLAY_RGB_MAX_PIXELS,
    PROYECTO_DIR,
    RGB_STRETCH,
    TILE_SIZE,
    WEB_MERCATOR_CRS,
)
from backend.core.state import (
    DEFAULT_INGESTA_INFO,
    DEFAULT_STATE,
    EXTENSIONES_VALIDAS,
    app_title,
    camera_model_actual,
    curvas_nivel_cache,
    es_rededge_m_actual,
    es_solo_rgb_actual,
    ingesta_info,
    lock,
    limpiar_salidas_proyecto,
    logs,
    nombre_proyecto_actual,
    overlay_cache,
    process,
    push_log,
    reader_thread,
    reset_runtime_state,
    shapefile_overlay_cache,
    snapshot_ingesta_info,
    snapshot_logs,
    snapshot_state,
    state,
    update_ingesta_info,
    update_state,
)

__all__ = [
    "BASE_DIR",
    "CONTOURS_SCRIPT",
    "DEFAULT_CAMERA_MODEL",
    "DEFAULT_INGESTA_INFO",
    "DEFAULT_PROJECT_NAME",
    "DEFAULT_STATE",
    "EARTH_RADIUS",
    "EXTENSIONES_VALIDAS",
    "FRONTEND_DIST_DIR",
    "FRONTEND_INDEX_FILE",
    "LOGS_DIR",
    "MAIN_SCRIPT",
    "MAX_TILE_ZOOM",
    "METASHAPE_EXE",
    "OVERLAY_RGB_MAX_PIXELS",
    "PROYECTO_DIR",
    "RGB_STRETCH",
    "RUTA_IMAGENES",
    "TILE_SIZE",
    "WEB_MERCATOR_CRS",
    "_frontend_dist_path",
    "app_title",
    "camera_model_actual",
    "curvas_nivel_cache",
    "es_rededge_m_actual",
    "es_solo_rgb_actual",
    "ingesta_info",
    "limpiar_salidas_proyecto",
    "lock",
    "logs",
    "nombre_proyecto_actual",
    "normalizar_modelo_camara",
    "overlay_cache",
    "process",
    "push_log",
    "reader_thread",
    "reset_runtime_state",
    "sanitizar_nombre_proyecto",
    "serve_frontend_index",
    "shapefile_overlay_cache",
    "snapshot_ingesta_info",
    "snapshot_logs",
    "snapshot_state",
    "state",
    "update_ingesta_info",
    "update_state",
]
